[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "ssd"
version = "0.2.0"
authors = [{ name = "Tanishq Kumar" }]
license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"
description = "Async tree-based speculative decoding research engine"
requires-python = ">=3.11,<3.13"
dependencies = [
    "torch==2.11.0",
    "triton",
    "transformers>=5.3.0",
    "xxhash",
    "numpy",
    "safetensors",
    "tqdm",
    "sglang-kernel==0.4.2.post1",  # Make sure this version is synchronized with TGL
    "nvidia-cutlass-dsl>=4.3.4",
    "wandb==0.22.0",
    "hf_transfer",
    "tiktoken",
    "flash-attn-4>=4.0.0b9",
]

[project.urls]
Homepage="https://github.com/tanishqkumar/ssd"

[tool.setuptools.packages.find]
where = ["."]
include = ["ssd*"]
